#include "bits/stdc++.h"

// https://www.spoj.com/problems/MIXTURES/

using namespace std;

#define int long long
#define HAVE_TESTCASES 0

const int INF = (int) 1e18;
const int MOD = (int) (1e9 + 7);

void solve() {
  int n;
  while (cin >> n) {
    vector<int> arr(n);
    vector<int> ps(n+1, 0); // prefix sum
    for (int i=0; i < n; i++) {
      cin >> arr[i];
      ps[i+1] = ps[i] + arr[i];
    }
    vector<vector<int>> dp(n, vector<int>(n, INF)); // dp[l][r] = min amount of smoke in interval [l,r]
    for (int i=0; i < n; i++) dp[i][i] = 0; // no smoke from single mixture
    for (int len=2; len <= n; len++) {
      for (int l=0; l + len - 1 < n; l++) {
        int r = l + len - 1;
        for (int k=l; k < r; k++) {
          int a = ps[k+1] - ps[l]; // new color of mixture made by combining all colors in range [l, k] 
          int b = ps[r+1] - ps[k+1]; // combining all colors in range [k+1, r]
          int smoke = (a % 100) * (b % 100); // final smoke generated by merging first range and second range
          dp[l][r] = min(dp[l][r], dp[l][k] + dp[k+1][r] + smoke); // dp[l][k] and dp[k+1][r] is internal smoke genrated in combining colors in respective ranges
        }
      }
    }
    cout << dp[0][n-1] << "\n";
  }
}

#undef int
int main() {
  ios_base::sync_with_stdio(false);
  cin.tie(0);
  cout << setprecision(10);
#if HAVE_TESTCASES
  int t;
  cin >> t;
  while (t--) solve();
#else
  solve();
#endif
}

